// Providers
export const PROVIDERS_REQUEST = "PROVIDERS_REQUEST";
export const PROVIDERS_SUCCESS = "PROVIDERS_SUCCESS";
export const PROVIDERS_ERROR = "PROVIDERS_ERROR";

// Locations
export const LOCATIONS_REQUEST = "LOCATIONS_REQUEST";
export const LOCATIONS_SUCCESS = "LOCATIONS_SUCCESS";
export const LOCATIONS_ERROR = "LOCATIONS_ERROR";
